### ISSUE TITLE
default config fails to start when pem file not found

### ISSUE THREAD

**Issue by miketheman** [Netflix/dynomite#96]
Introduced in #57.

The [default config](https://github.com/Netflix/dynomite/blob/438b6dbbb49fbca64897d46badcc7dc1562da7b7/conf/dynomite.yml) has no configuration set for crypto, yet it attempts to load it by default, and fails when not found.

```
root@4622f90515db:~# pwd
/root
root@4622f90515db:~# which dynomite
/usr/local/sbin/dynomite
root@4622f90515db:~# dynomite -c dynomite/conf/dynomite.yml
[Sun Mar 15 16:17:35 2015] dynomite.c:194 dynomite-0.1.19 built for Linux 3.18.5-tinycore64 x86_64 started on pid 8668
[Sun Mar 15 16:17:35 2015] dynomite.c:199 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one
[Sun Mar 15 16:17:35 2015] dyn_crypto.c:45 Error: file conf/dynomite.pem not exists
[Sun Mar 15 16:17:35 2015] dyn_core.c:87 Failed to initialize crypto!!!
[Sun Mar 15 16:17:35 2015] dynomite.c:205 done, rabbit done
root@4622f90515db:~#
```

The error message comes from https://github.com/Netflix/dynomite/blob/438b6dbbb49fbca64897d46badcc7dc1562da7b7/src/dyn_crypto.c#L44-L47 - which makes sense, as the default-set path of `conf/dynomite.pem` is not reachable from the current path, however this should not be loaded until a `pem_key_file` setting is added in the config.

This is likely due to the definition here: https://github.com/Netflix/dynomite/blob/438b6dbbb49fbca64897d46badcc7dc1562da7b7/src/dyn_conf.h#L86 which is inherited by all configurations, even when unspecified.

I _think_ this shouldn't be declared as a constant, rather some empty value that does not attempt to initialize crypto on startup when the parameter is not set.

**Comment by timiblossom** [comment]
This makes sense.  Will fix this. Thanks.

**Comment by nimeops** [comment]
Hi.
Seems to be always broken??

**Comment by nimeops** [comment]
hi,
something i don't understand.

On several servers, no problem if there is no crypto (no pem file), and others, we've got following error:
 
load_private_rsa_key_by_file:44 Error: file conf/dynomite.pem does not exist
load_private_rsa_key:112 failed load_private_rsa_key_by_file(&sp->pem_key_file)
crypto_pool_each_init:157 failed load_private_rsa_key(sp)
crypto_init:166 failed array_each(&ctx->pool, crypto_pool_each_init, NULL)
core_ctx_create:79 Failed to initialize crypto!!!
dn_print_done:217 done, rabbit done

An idea??

**Comment by vietcgi** [comment]
i had the same issue with the latest version.

**Comment by BarthV** [comment]
+1

**Comment by BarthV** [comment]
found a workaround by creating a dummy pem certificate & giving key & iv pem files with `0123456789` in it :

dynomite.yml :
```
  pem_key_file: /etc/dynomite/dynomite.pem
  recon_key_file: /etc/dynomite/recon_key.pem
  recon_iv_file: /etc/dynomite/recon_iv.pem
```

**Comment by smukil** [comment]
Closing since resolved
