### ISSUE TITLE
Dynomite doesn't compile with OpenSSL 1.1

### ISSUE THREAD

**Issue by shunanya** [Netflix/dynomite#510]
Hi,

Unfortunately, Dynomite (0.6.x) couldn't be establishing due to compilation error () on my Debian GNU/Linux 8 (jessie) with OpenSSL 1.1.0g. 
```
dyn_crypto.c:129:55: error: invalid application of ‘sizeof’ to incomplete type ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
     aes_encrypt_ctx = (EVP_CIPHER_CTX*) malloc(sizeof(EVP_CIPHER_CTX));

``` 
The same picture was detected by using previous versions of Dynomit (0.5.8 and less). 
The compilation error has disappeared when I did downgrade OpenSSL up to version 1.0.2. 
I hope this mistake can be corrected quite soon.
Simon

**Comment by woutd** [comment]
Hello

I made the following changes to make it compile on Debian 9 (stretch) with OpenSSL 1.1.0f. **Have not tested anything else though.**

```
diff --git a/src/dyn_crypto.c b/src/dyn_crypto.c
index afcfe83..a023a58 100644
--- a/src/dyn_crypto.c
+++ b/src/dyn_crypto.c
@@ -126,8 +126,20 @@ static rstatus_t
 aes_init(void)
 {
     // Initialize contexts
+#if OPENSSL_VERSION_NUMBER >= 0x1010000fL
+    aes_encrypt_ctx = EVP_CIPHER_CTX_new();
+    if (aes_encrypt_ctx == NULL) {
+        return DN_ERROR;
+    }
+
+    aes_decrypt_ctx = EVP_CIPHER_CTX_new();
+    if (aes_decrypt_ctx == NULL) {
+        return DN_ERROR;
+    }
+#else
     aes_encrypt_ctx = (EVP_CIPHER_CTX*) malloc(sizeof(EVP_CIPHER_CTX));
     aes_decrypt_ctx = (EVP_CIPHER_CTX*) malloc(sizeof(EVP_CIPHER_CTX));
+#endif
 
     EVP_CIPHER_CTX_init(aes_encrypt_ctx);
 
@@ -173,10 +185,15 @@ crypto_init(struct server_pool *sp)
 rstatus_t
 crypto_deinit(void)
 {
+#if OPENSSL_VERSION_NUMBER >= 0x1010000fL
+    EVP_CIPHER_CTX_free(aes_encrypt_ctx);
+    EVP_CIPHER_CTX_free(aes_decrypt_ctx);
+#else
     EVP_CIPHER_CTX_cleanup(aes_encrypt_ctx);
     EVP_CIPHER_CTX_cleanup(aes_decrypt_ctx);
     free(aes_encrypt_ctx);
     free(aes_decrypt_ctx);
+#endif
     return DN_OK;
 }
 
```

**Comment by shailesh33** [comment]
Thank you  @woutd. Appreciate your efforts here. One of the primary requirement for a change like this is backward compatibility to make sure the new binary and old binary can still work with each other. The reason being we do in place upgrades of one node at a time so it should work in a heterogenous Dynomite version environment.

**Comment by woutd** [comment]
I am only starting to experiment with Dynomite. My test setup will include one instance running Debian 7.11 (wheezy) with OpenSSL 1.0.1t. In case I run into issues with the above patch, I will let you know.

**Comment by mbardelmeijer** [comment]
Any update on OpenSSL 1.1.* support? Prefer not to run a patched version in production nor downgrade OpenSSL :)

**Comment by pashinin** [comment]
Was there a pull request with that patch? Is there a reason not to include it if it's working?

**Comment by woutd** [comment]
My above patch made it compile with newer versions of OpenSSL, but if I remember correctly, caused issues during runtime. I do not recommend using it.

**Comment by lenw** [comment]
I installed the `compat-openssl10-devel` in fedora and got it compiling that way

**Comment by kylegato** [comment]
I was able to compile/get past this problem on Debian (9.5) by installing `libssl1.0-dev` instead of `libssl-dev`
